stages:  
  preparation:
    cmd: python scripts/cleaning_stage.py #data/prepared data/features
    deps:
      #- data/prepared
      - scripts/cleaning_stage.py
    params:
      - preparation.version
      - preparation.fromThe
      - preparation.missing_values
      #- featurize.ngrams
    #outs:
      #- data/features